"""add_chunk_metadata_fields

Revision ID: eb7b32fecfc8
Revises: 3eca4b4d8445
Create Date: 2026-03-18 16:45:18.663393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb7b32fecfc8'
down_revision: Union[str, None] = '3eca4b4d8445'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('code_chunks', sa.Column('docstring', sa.Text(), nullable=False))
    op.add_column('code_chunks', sa.Column('parent_name', sa.String(length=300), nullable=False))
    op.add_column('code_chunks', sa.Column('display_name', sa.String(length=600), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('code_chunks', 'display_name')
    op.drop_column('code_chunks', 'parent_name')
    op.drop_column('code_chunks', 'docstring')
    # ### end Alembic commands ###
