"""add_chunk_metadata_fields

Revision ID: f163e94dc01f
Revises: 6178f0eb8913
Create Date: 2026-04-12 15:30:29.523899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f163e94dc01f'
down_revision: Union[str, None] = '6178f0eb8913'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('code_chunks', sa.Column('docstring', sa.Text(), nullable=False))
    op.add_column('code_chunks', sa.Column('parent_name', sa.String(length=300), nullable=False))
    op.add_column('code_chunks', sa.Column('display_name', sa.String(length=600), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('code_chunks', 'display_name')
    op.drop_column('code_chunks', 'parent_name')
    op.drop_column('code_chunks', 'docstring')
    # ### end Alembic commands ###